[package]
name = "demo"
version = "0.1.0"
authors = ["Sunshine Foundation Developers", "Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
log = "0.4"
fastrand = "^1"
frusty-logger = { path = "../frusty-logger" }

