name: frusty_logger
description: A Bridge between Rust log crate and Flutter
version: 0.1.0
author: Sunshine Foundation Developers
homepage:

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.10.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: foundation.sunshine.frusty_logger
        pluginClass: FrustyLoggerPlugin
      ios:
        pluginClass: FrustyLoggerPlugin
